### PA2

Normalization Problem

In [ ]:
import numpy as np

X = np.random.randint(1, 101, size = (5, 5)) #create a random 5x5 array
print("Original 5x5 random array X:")
print(X)

np.save("X_normalized.npy", X) #save the array to a .npy file

Original 5x5 random array X:
[[316  50 190 212 430]
 [452  24 209 130  52]
 [490  65 357 455  29]
 [442 367 438 222 451]
 [332  39 471 129  28]]


In [60]:
original_arr = np.load('X_normalized.npy') #to call the random array

X_normalized = (X-X.mean())/X.std() #to normalize

#to print the results
print("The original Array is: \n", original_arr)
print("The normalized Array is: \n",X_normalized)


The original Array is: 
 [[316  50 190 212 430]
 [452  24 209 130  52]
 [490  65 357 455  29]
 [442 367 438 222 451]
 [332  39 471 129  28]]
The normalized Array is: 
 [[ 0.3598901  -1.21462909 -0.38593478 -0.25571139  1.03468404]
 [ 1.16490743 -1.36852946 -0.27346912 -0.74108948 -1.2027906 ]
 [ 1.38983874 -1.12584041  0.60257915  1.18266516 -1.33893323]
 [ 1.10571498  0.6617716   1.082038   -0.19651894  1.15898818]
 [ 0.45459802 -1.27974078  1.27737308 -0.74700873 -1.34485248]]


Divisible by 3 Problem

In [61]:
import numpy as np

integers = np.arange(1, 101) # First, create array of integers 1 to 100

squares = integers ** 2 # Square them to get 1², 2², 3², ..., 100²

A = squares.reshape(10, 10) # Reshape into 10x10 array

print("Squares of first 100 positive integers:")
print(A)

Squares of first 100 positive integers:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [ ]:
div_by_3 = A[A % 3 == 0] # Find elements divisible by 3

np.save("div_by_3.npy", div_by_3) #Save the numbers as "div_by_3.npy"

Num_div_by_3 = np.load("div_by_3.npy") #Load the saved file

print(f"\nElements in A that are divisible by 3: \n", Num_div_by_3)
print(f"\nNumber of elements divisible by 3: {len(Num_div_by_3)}")


Elements in A that are divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Number of elements divisible by 3: 33
